services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpwd
      MYSQL_DATABASE: foncier
      MYSQL_USER: user
      MYSQL_PASSWORD: userpwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafanapwd

volumes:
  mysql_data:
  grafana_data:
